# nginx proxy address - http://172.17.0.1:8384

name: syncthing
x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  syncthing:
    image: syncthing/syncthing:latest
    pull_policy: always
    container_name: syncthing-app
    hostname: ${BASE_HOST_NAME:-$HOSTNAME}
    restart: always
    logging: *default-logging
    networks:
      - syncthing
      - proxy
      - cloudflare
    ports:
      - "172.17.0.1:8384:8384"
      - "22000:22000/tcp"
      - "22000:22000/udp"
      - "21027:21027/udp"
    environment:
      TZ: ${TZ:-America/New_York}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
      CONTAINER_NAME: syncthing-app
      HOSTNAME: ${BASE_HOST_NAME:-$HOSTNAME}
    volumes:
      - ./volumes/config/syncthing:/var/syncthing/config
      - ./volumes/data/syncthing:/var/syncthing/Sync
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8384"]
      interval: 30s
      timeout: 10s
      retries: 3
    labels:
      - 'traefik.enable=true'
      - 'cloudflare.enable=true'
      - 'traefik.docker.network=proxy'
      - 'cloudflare.service=http://syncthing-app:8384'
      - 'cloudflare.hostname=syncthing.${CLOUDFLARE_ZONE_NAME:-}'
      - 'traefik.http.routers.syncthing-app.entrypoints=http'
      - 'traefik.http.routers.syncthing-app-secure.tls=true'
      - 'traefik.http.routers.syncthing-app.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.middlewares.syncthing-app-https-redirect.redirectscheme.scheme=https'
      - 'traefik.http.routers.syncthing-app.middlewares=syncthing-app-https-redirect'
      - 'traefik.http.routers.syncthing-app-secure.entrypoints=https'
      - 'traefik.http.routers.syncthing-app-secure.rule=Host($(${BASE_HOST_NAME:-$HOSTNAME}))'
      - 'traefik.http.routers.syncthing-app-secure.tls.certresolver=cloudflare'
      - 'traefik.http.routers.syncthing-app-secure.service=syncthing-app'
      - 'traefik.http.services.syncthing-app.loadbalancer.server.port=8384'

networks:
  syncthing:
    name: syncthing
    external: false
  proxy:
    external: true
  cloudflare:
    external: true
