# nginx proxy address - http://172.17.0.1:8384

x-logging: &default-logging
  driver: json-file
  options:
    max-size: "5m"
    max-file: "1"

services:
  syncthing:
    image: syncthing/syncthing:latest
    container_name: syncthing-app
    restart: unless-stopped
    logging: *default-logging
    networks:
      - syncthing
    ports:
      - "8384:8384"
    environment:
      TZ: ${TZ:-America/New_York}
      PUID: ${SERVICE_USER:-1000}
      PGID: ${SERVICE_GROUP:-1000}
    volumes:
      - ./rootfs/config/syncthing:/config
      - ./rootfs/data/syncthing:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8384"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  syncthing:
    external: false
